//
//  MetroArea
//  venueSearch
//
//  Created by Stu Almeleh on 5/4/16.
//  Copyright © 2016 Stu Almeleh. All rights reserved.
//

import Foundation

struct MetroArea {
    
    //MARK: Properites
    var uri: String
    var displayName: String
    var country: String
    var id: Int
    var lng: Double
    var lon: Double
    
    //MARK: Methods
    
    //MARK: JSON Body Keys

    //MARK: JSON Response Keys

    
    
}